### ISSUE TITLE
IOError: [Errno 2] No such file or directory: './states/s0.jpg'

### ISSUE THREAD

**Issue by theparadoxofparadox** [7yl4r/neuroSemantics#4]
Running the main.py file gives the following error:

> WARN: range <= 0
> conn stren m: 100.0     v: 0
> adjustment m: 2900.0    v: 0
> Traceback (most recent call last):
>   File "main.py", line 40, in <module>
>     network.input_file('./input_scripts/base.txt')
>   File "/Users/school/Github/neuroSemantics/Network.py", line 175, in input_file
>     self.plot_state_file()
>   File "/Users/school/Github/neuroSemantics/Network.py", line 162, in plot_state_file
>     self.state.plot_img('./states/s' + str(self.input_count) + '.jpg')
>   File "/Users/school/Github/neuroSemantics/NetworkState.py", line 69, in plot_img
>     img.save(save_file_loc)
>   File "/Library/Python/2.7/site-packages/PIL/Image.py", line 1684, in save
>     fp = builtins.open(filename, "wb")
> IOError: [Errno 2] No such file or directory: './states/s0.jpg'

I have looked around for a bit, what exactly am I doing wrong?? I feel like it could be a problem with my PIL installation (installed via `pip install pillow` )

**Comment by 7yl4r** [comment]
It's been a while since I've played with this project, but I think you're right that PIL is a likely candidate. I remember the install process being unusual.

Here's a quote from the readme of one of my more user-friendly projects ([Lifegenes](https://github.com/7yl4r/LifeGenes)) which might be helpful:

> [PIL](http://www.pythonware.com/products/pil/) - Python imaging library is for using images with Tkinter to create GUI elements such as the genetic cell painter pallate. Win32 binaries and source for linux can be found on the linked project page. Additional binaries (including 64bit) can be found [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pil), and alternative source can be found in the [Pillow repo](https://github.com/python-imaging/Pillow).

I believe I used the same basic PIL methodology for this project. 

This project isn't a bit of a incomplete stub so I'm surprised to see interest here. Anything in particular you are interested in?

**Comment by theparadoxofparadox** [comment]
Yeah it is an unusual install process. I decided after many failed attempts to use a virtual environment, start fresh and only install the exact dependencies. Got me further into the installation however I continue to run into some errors, I feel I am close to success though. 

Ahh...interesting, I'll have a look at that and see if it helps!

I have just been doing lots of research recently on neural networks and machine learning and when I came across this project the description fascinated me, it made me think about the possible applications for the working version. This is my first foray into any sort of machine learning, I have read a lot and I just want to get my hands dirty now. It's hard sometimes because I don't have anyone I can talk to about things I find or questions I have (my high school is definitely nowhere near equipped for this kind of programming, the teachers heads may explode). 
Just looking to gain a bit of practical experience and such, this project really interests me!

**Comment by 7yl4r** [comment]
Hey @HighDensityAwesome, this is a bit random but I came across this the other day and perhaps it will help re-ignite any interest my little stub project may have eaten: http://playground.tensorflow.org/

I haven't looked at the source code yet, but superficially that looks like a great starting point for lots of projects and the project itself is probably the best I've seen for basic exploring of ANNs.
